controller_list:
  - name: fake_fl_controller
    joints:
      - lf_hinge_1
      - lf_hinge_2
      - lf_hinge_3
      - lf_hinge_4
  - name: fake_end_fl_controller
    joints:
      - lf_hinge_4
  - name: fake_lr_controller
    joints:
      - lr_hinge_1
      - lr_hinge_2
      - lr_hinge_3
      - lr_hinge_4
  - name: fake_end_lr_controller
    joints:
      - lr_hinge_4
  - name: fake_rr_controller
    joints:
      - jrr_hinge_1
      - jrr_hinge_2
      - jrr_hinge_3
      - jrr_hinge_4
  - name: fake_end_rr_controller
    joints:
      - jrr_hinge_4
  - name: fake_rf_controller
    joints:
      - rf_hinge_1
      - rf_hinge_2
      - rf_hinge_3
      - rf_hinge_4
  - name: fake_end_rf_controller
    joints:
      - rf_hinge_4
initial:  # Define initial robot poses.
  - group: fl
    pose: Pose_1
  - group: lr
    pose: Pose_2
  - group: rr
    pose: Pose_3
  - group: rf
    pose: Pose_4